// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cond_dvine1_cpp
Eigen::MatrixXd cond_dvine1_cpp(const int n_samples, const double cond_alpha, const Rcpp::List& vinecop_r);
RcppExport SEXP _portvine_cond_dvine1_cpp(SEXP n_samplesSEXP, SEXP cond_alphaSEXP, SEXP vinecop_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< const double >::type cond_alpha(cond_alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type vinecop_r(vinecop_rSEXP);
    rcpp_result_gen = Rcpp::wrap(cond_dvine1_cpp(n_samples, cond_alpha, vinecop_r));
    return rcpp_result_gen;
END_RCPP
}
// cond_dvine2_cpp
Eigen::MatrixXd cond_dvine2_cpp(const int n_samples, const double cond_alpha, const Rcpp::List& vinecop_r);
RcppExport SEXP _portvine_cond_dvine2_cpp(SEXP n_samplesSEXP, SEXP cond_alphaSEXP, SEXP vinecop_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< const double >::type cond_alpha(cond_alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type vinecop_r(vinecop_rSEXP);
    rcpp_result_gen = Rcpp::wrap(cond_dvine2_cpp(n_samples, cond_alpha, vinecop_r));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_portvine_cond_dvine1_cpp", (DL_FUNC) &_portvine_cond_dvine1_cpp, 3},
    {"_portvine_cond_dvine2_cpp", (DL_FUNC) &_portvine_cond_dvine2_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_portvine(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
