# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bicop_pdf_cpp <- function(u, bicop_r) {
    .Call(`_portvine_bicop_pdf_cpp`, u, bicop_r)
}

bicop_cdf_cpp <- function(u, bicop_r) {
    .Call(`_portvine_bicop_cdf_cpp`, u, bicop_r)
}

bicop_hfunc1_cpp <- function(u, bicop_r) {
    .Call(`_portvine_bicop_hfunc1_cpp`, u, bicop_r)
}

bicop_hfunc2_cpp <- function(u, bicop_r) {
    .Call(`_portvine_bicop_hfunc2_cpp`, u, bicop_r)
}

bicop_hinv1_cpp <- function(u, bicop_r) {
    .Call(`_portvine_bicop_hinv1_cpp`, u, bicop_r)
}

bicop_hinv2_cpp <- function(u, bicop_r) {
    .Call(`_portvine_bicop_hinv2_cpp`, u, bicop_r)
}

bicop_loglik_cpp <- function(u, bicop_r) {
    .Call(`_portvine_bicop_loglik_cpp`, u, bicop_r)
}

